database:
  driverClass: org.sqlite.JDBC
  url: 'jdbc:sqlite:unit-test.db'
  properties:
    charSet: UTF-8

maxConnections: 1024

queue:
  tableName: queasy_q
  ringBufferSize: 1024
  insertBatchSize: 2
  maxSize: 10000


consumerGroups:
  testCG:
    queueName: testQ
    selectBatchSize: 2
