database:
  driverClass: org.sqlite.JDBC
  url: 'jdbc:sqlite:unit-test.db'
  properties:
    charSet: UTF-8

maxConnections: 1024

queue:
  tableName: queasy_q
  maxSize: 10000

consumerGroups:
  default:
