package org.queasy;

/**
 * @author saroskar
 * Created on: 2021-03-24
 */
public class ToDo {

    //-  See if LastAutoGeneratedIdFinder can be replaced with a single select last_inserted_id();
    //-  send message to consumer as <id>\n<message>
    //-  Timeout with #GET
    //-  #NACK from consumer to push message back on the queue?
    //-  Integration test(s)
    //-  QueueTrimmerTask using lifecycle scheduler builder
    //-  Health check
    //-  Replication - add partition as non unique key column?
    //-  Subscriber topic
    //-  Metrics using DW
}
